# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import fits_pb2 as ifs_dot_fits_dot_fits__pb2


class FitsSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Find = channel.unary_unary(
        '/ifs.fits.FitsSrv/Find',
        request_serializer=ifs_dot_fits_dot_fits__pb2.FindRawFitsReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.FindRawFitsResp.FromString,
        )
    self.Get = channel.unary_unary(
        '/ifs.fits.FitsSrv/Get',
        request_serializer=ifs_dot_fits_dot_fits__pb2.GetRawFitsReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.GetRawFitsResp.FromString,
        )
    self.Read = channel.unary_stream(
        '/ifs.fits.FitsSrv/Read',
        request_serializer=ifs_dot_fits_dot_fits__pb2.ReadRawFitsReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.ReadRawFitsResp.FromString,
        )
    self.Write = channel.stream_unary(
        '/ifs.fits.FitsSrv/Write',
        request_serializer=ifs_dot_fits_dot_fits__pb2.WriteRawFitsReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.WriteRawFitsResp.FromString,
        )
    self.UpdateQc0Status = channel.unary_unary(
        '/ifs.fits.FitsSrv/UpdateQc0Status',
        request_serializer=ifs_dot_fits_dot_fits__pb2.UpdateQc0StatusReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.UpdateQc0StatusResp.FromString,
        )
    self.UpdateProcStatus = channel.unary_unary(
        '/ifs.fits.FitsSrv/UpdateProcStatus',
        request_serializer=ifs_dot_fits_dot_fits__pb2.UpdateProcStatusReq.SerializeToString,
        response_deserializer=ifs_dot_fits_dot_fits__pb2.UpdateProcStatusResp.FromString,
        )


class FitsSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Find(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateQc0Status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProcStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FitsSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Find': grpc.unary_unary_rpc_method_handler(
          servicer.Find,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.FindRawFitsReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.FindRawFitsResp.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.GetRawFitsReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.GetRawFitsResp.SerializeToString,
      ),
      'Read': grpc.unary_stream_rpc_method_handler(
          servicer.Read,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.ReadRawFitsReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.ReadRawFitsResp.SerializeToString,
      ),
      'Write': grpc.stream_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.WriteRawFitsReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.WriteRawFitsResp.SerializeToString,
      ),
      'UpdateQc0Status': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateQc0Status,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.UpdateQc0StatusReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.UpdateQc0StatusResp.SerializeToString,
      ),
      'UpdateProcStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProcStatus,
          request_deserializer=ifs_dot_fits_dot_fits__pb2.UpdateProcStatusReq.FromString,
          response_serializer=ifs_dot_fits_dot_fits__pb2.UpdateProcStatusResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ifs.fits.FitsSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
