# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import level2spectra_pb2 as sls_dot_level2spectra_dot_level2spectra__pb2


class Level2spectraSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Find = channel.unary_unary(
        '/dfs.sls.level2spectra.Level2spectraSrv/Find',
        request_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.FindLevel2spectraReq.SerializeToString,
        response_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.FindLevel2spectraResp.FromString,
        )
    self.Get = channel.unary_unary(
        '/dfs.sls.level2spectra.Level2spectraSrv/Get',
        request_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.GetLevel2spectraReq.SerializeToString,
        response_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.GetLevel2spectraResp.FromString,
        )
    self.Write = channel.stream_unary(
        '/dfs.sls.level2spectra.Level2spectraSrv/Write',
        request_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.WriteLevel2spectraReq.SerializeToString,
        response_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.WriteLevel2spectraResp.FromString,
        )
    self.UpdateQc1Status = channel.unary_unary(
        '/dfs.sls.level2spectra.Level2spectraSrv/UpdateQc1Status',
        request_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateQc1StatusReq.SerializeToString,
        response_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateQc1StatusResp.FromString,
        )
    self.UpdateProcStatus = channel.unary_unary(
        '/dfs.sls.level2spectra.Level2spectraSrv/UpdateProcStatus',
        request_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateProcStatusReq.SerializeToString,
        response_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateProcStatusResp.FromString,
        )


class Level2spectraSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Find(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateQc1Status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateProcStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Level2spectraSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Find': grpc.unary_unary_rpc_method_handler(
          servicer.Find,
          request_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.FindLevel2spectraReq.FromString,
          response_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.FindLevel2spectraResp.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.GetLevel2spectraReq.FromString,
          response_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.GetLevel2spectraResp.SerializeToString,
      ),
      'Write': grpc.stream_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.WriteLevel2spectraReq.FromString,
          response_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.WriteLevel2spectraResp.SerializeToString,
      ),
      'UpdateQc1Status': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateQc1Status,
          request_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateQc1StatusReq.FromString,
          response_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateQc1StatusResp.SerializeToString,
      ),
      'UpdateProcStatus': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateProcStatus,
          request_deserializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateProcStatusReq.FromString,
          response_serializer=sls_dot_level2spectra_dot_level2spectra__pb2.UpdateProcStatusResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dfs.sls.level2spectra.Level2spectraSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
