# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import brick_pb2 as facility_dot_brick_dot_brick__pb2


class BrickSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Find = channel.unary_unary(
        '/dfs.facility.brick.BrickSrv/Find',
        request_serializer=facility_dot_brick_dot_brick__pb2.FindBrickReq.SerializeToString,
        response_deserializer=facility_dot_brick_dot_brick__pb2.FindBrickResp.FromString,
        )
    self.Get = channel.unary_unary(
        '/dfs.facility.brick.BrickSrv/Get',
        request_serializer=facility_dot_brick_dot_brick__pb2.GetBrickReq.SerializeToString,
        response_deserializer=facility_dot_brick_dot_brick__pb2.GetBrickResp.FromString,
        )
    self.Write = channel.unary_unary(
        '/dfs.facility.brick.BrickSrv/Write',
        request_serializer=facility_dot_brick_dot_brick__pb2.WriteBrickReq.SerializeToString,
        response_deserializer=facility_dot_brick_dot_brick__pb2.WriteBrickResp.FromString,
        )
    self.FindObsStatus = channel.unary_unary(
        '/dfs.facility.brick.BrickSrv/FindObsStatus',
        request_serializer=facility_dot_brick_dot_brick__pb2.FindObsStatusReq.SerializeToString,
        response_deserializer=facility_dot_brick_dot_brick__pb2.FindObsStatusResp.FromString,
        )
    self.FindLevel1 = channel.unary_unary(
        '/dfs.facility.brick.BrickSrv/FindLevel1',
        request_serializer=facility_dot_brick_dot_brick__pb2.FindLevel1Req.SerializeToString,
        response_deserializer=facility_dot_brick_dot_brick__pb2.FindLevel1Resp.FromString,
        )


class BrickSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Find(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindObsStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindLevel1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BrickSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Find': grpc.unary_unary_rpc_method_handler(
          servicer.Find,
          request_deserializer=facility_dot_brick_dot_brick__pb2.FindBrickReq.FromString,
          response_serializer=facility_dot_brick_dot_brick__pb2.FindBrickResp.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=facility_dot_brick_dot_brick__pb2.GetBrickReq.FromString,
          response_serializer=facility_dot_brick_dot_brick__pb2.GetBrickResp.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=facility_dot_brick_dot_brick__pb2.WriteBrickReq.FromString,
          response_serializer=facility_dot_brick_dot_brick__pb2.WriteBrickResp.SerializeToString,
      ),
      'FindObsStatus': grpc.unary_unary_rpc_method_handler(
          servicer.FindObsStatus,
          request_deserializer=facility_dot_brick_dot_brick__pb2.FindObsStatusReq.FromString,
          response_serializer=facility_dot_brick_dot_brick__pb2.FindObsStatusResp.SerializeToString,
      ),
      'FindLevel1': grpc.unary_unary_rpc_method_handler(
          servicer.FindLevel1,
          request_deserializer=facility_dot_brick_dot_brick__pb2.FindLevel1Req.FromString,
          response_serializer=facility_dot_brick_dot_brick__pb2.FindLevel1Resp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dfs.facility.brick.BrickSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
