# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ephem_pb2 as common_dot_ephem_dot_ephem__pb2


class EphemSearchSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Gaia2Search = channel.unary_unary(
        '/dfs.ephem.EphemSearchSrv/Gaia2Search',
        request_serializer=common_dot_ephem_dot_ephem__pb2.EphemSearchRequest.SerializeToString,
        response_deserializer=common_dot_ephem_dot_ephem__pb2.Gaia2SearchResponse.FromString,
        )


class EphemSearchSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Gaia2Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EphemSearchSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Gaia2Search': grpc.unary_unary_rpc_method_handler(
          servicer.Gaia2Search,
          request_deserializer=common_dot_ephem_dot_ephem__pb2.EphemSearchRequest.FromString,
          response_serializer=common_dot_ephem_dot_ephem__pb2.Gaia2SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dfs.ephem.EphemSearchSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
